// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: grpc/template.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Template_Student_FullMethodName = "/proto.Template/student"
)

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateClient interface {
	Student(ctx context.Context, opts ...grpc.CallOption) (Template_StudentClient, error)
}

type templateClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateClient(cc grpc.ClientConnInterface) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) Student(ctx context.Context, opts ...grpc.CallOption) (Template_StudentClient, error) {
	stream, err := c.cc.NewStream(ctx, &Template_ServiceDesc.Streams[0], Template_Student_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &templateStudentClient{stream}
	return x, nil
}

type Template_StudentClient interface {
	Send(*Greeting) error
	Recv() (*Farewell, error)
	grpc.ClientStream
}

type templateStudentClient struct {
	grpc.ClientStream
}

func (x *templateStudentClient) Send(m *Greeting) error {
	return x.ClientStream.SendMsg(m)
}

func (x *templateStudentClient) Recv() (*Farewell, error) {
	m := new(Farewell)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TemplateServer is the server API for Template service.
// All implementations must embed UnimplementedTemplateServer
// for forward compatibility
type TemplateServer interface {
	Student(Template_StudentServer) error
	mustEmbedUnimplementedTemplateServer()
}

// UnimplementedTemplateServer must be embedded to have forward compatible implementations.
type UnimplementedTemplateServer struct {
}

func (UnimplementedTemplateServer) Student(Template_StudentServer) error {
	return status.Errorf(codes.Unimplemented, "method Student not implemented")
}
func (UnimplementedTemplateServer) mustEmbedUnimplementedTemplateServer() {}

// UnsafeTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServer will
// result in compilation errors.
type UnsafeTemplateServer interface {
	mustEmbedUnimplementedTemplateServer()
}

func RegisterTemplateServer(s grpc.ServiceRegistrar, srv TemplateServer) {
	s.RegisterService(&Template_ServiceDesc, srv)
}

func _Template_Student_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TemplateServer).Student(&templateStudentServer{stream})
}

type Template_StudentServer interface {
	Send(*Farewell) error
	Recv() (*Greeting, error)
	grpc.ServerStream
}

type templateStudentServer struct {
	grpc.ServerStream
}

func (x *templateStudentServer) Send(m *Farewell) error {
	return x.ServerStream.SendMsg(m)
}

func (x *templateStudentServer) Recv() (*Greeting, error) {
	m := new(Greeting)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Template_ServiceDesc is the grpc.ServiceDesc for Template service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Template_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "student",
			Handler:       _Template_Student_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/template.proto",
}
